### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by Technerder** [julius-speech/julius#103]
Does this library/project have a python wrapper?

**Comment by colbec** [comment]
If you do a search on "python julius" you will find a number of attempts at wrappers but curiously they do not seem to go anywhere. The reason for this might be that there is not a lot of additional functionality added by a generic wrapper. It is true that Julius is rarely used independently of some kind of environment; it might be one component alongside a database or a speech synthesiser for example, and then you need a wrapper such as Python to manage both the DB/synth and Julius at the same time. But then by this time the wrapper has become a specific app and not just a generic wrapper.

A programmer could certainly choose Python as a project manager to gain access to familiar libraries, but at some point Julius becomes a wild animal in a sack, doing things that the wrapper can't handle. At which point you have to abandon the generic and fork your own dialog manager.

**Comment by nitslp-ri** [comment]
No official python wrapper is included in Julius, but it is very easy to use Julius from python: execute Julius as another thread from the script, and capture its standard output and process it.
