### ISSUE TITLE
Realtime microphone recognition in Android APP

### ISSUE THREAD

**Issue by marco294** [julius-speech/julius#104]
Recently I have spent a lot of time to try to achieve the realtime microphone recognition in Android. However, I was trapped in cross compiling the library using the Android NDK such that I can use the microphone as input for Julius.

7 years ago, there was a [project](https://github.com/tech-sketch/JuliusForAndroid) that had successfully used the library in Android. But it only allowed to pass the RAW file / STDIN as the input for recognition. If you want to know more, there is a guideline on cross compile in this [project](https://github.com/tech-sketch/JuliusForAndroid).

After few [research](https://source.android.com/devices/audio), for most of the Android devices, the underlying audio system is using ALSA or OSS. And Julius should theoretically be able to use the microphone as input. However, the main step that I was trapped is the compiler cannot find the header file of any sound system (ALSA/OSS/others) and caused the compilation failed.

Did anyone success to compile the Julius using Android NDK and successfully use the microphone as input to do the voice recognition?

**Comment by nitslp-ri** [comment]
Julius supports PortAudio interface.  The original Portaudio does not support Android, but we have a version of PortAudio that supports Android (and iOS).  It can be availbale in the MMDAgent source code.  You can get it from:

https://sourceforge.net/p/mmdagent/code/HEAD/tree/MMDAgent/Library_PortAudio/

Fetch the library, build the Library_PortAudio for Android (see Android.mk in that package), and then, configure Julius to use libportaudio, and link to the library.
```
% configure --with-mictype=libportaudio
```

**Comment by marco294** [comment]
@nitslp-ri Thanks for the reply. I have successfully build the PortAudio for Android using ndk-build. However, I have trouble to configurate Julius to use portaudio. To use Julius on Android, I have to cross compile Julius for ARM using the android NDK. When I compile Julius, it requested the header and compiled files for portaudio. I set CPPFLAGS with -I${HEADER_DIR} and LDFLAGS with -L${COMPILED_CODE_DIR} for cross compiling Julius. 

But the finally it returns error stated that I can't include `<SLES/OpenSLES.h>` and `<SLES/OpenSLES_Android.h>` in file pa_android_opensles.c
```
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:114: error: undefined reference to 'slCreateEngine'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:345: error: undefined reference to 'SL_IID_ENGINE'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:345: error: undefined reference to 'SL_IID_BUFFERQUEUE'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:345: error: undefined reference to 'SL_IID_ANDROIDSIMPLEBUFFERQUEUE'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:345: error: undefined reference to 'SL_IID_ANDROIDCONFIGURATION'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:469: error: undefined reference to 'SL_IID_RECORD'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:469: error: undefined reference to 'SL_IID_PLAY'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:504: error: undefined reference to 'SL_IID_RECORD'
/Users/Desktop/final/android-ndk-r16b/jni/src/src/hostapi/opensles/pa_android_opensles.c:504: error: undefined reference to 'SL_IID_PLAY'
collect2: error: ld returned 1 exit status
make[1]: *** [julius] Error 1
```

Do you have any idea to solving this? Many thanks

**Comment by marco294** [comment]
Thanks to @nitslp-ri ! Finally this problem have been solved. I have cross compiled the [portaudio](https://github.com/Gundersanne/portaudio_opensles) from source code with the NDK instead of using ndk-build from the [project](https://github.com/Gundersanne/pa-android-tests) @nitslp-ri provided.

**Comment by tomsblueskeye** [comment]
@marco294 I am trying o use Julius on android too and struggling, could you explain how you got it to work?
