### ISSUE TITLE
adinrec : a couple of very strange problems

### ISSUE THREAD

**Issue by colbec** [julius-speech/julius#11]
Until now I have been using sox with the silence parameter to record prompts for HTK, but I think the VAD in adinrec is better for this purpose once a couple of problems are eliminated.

- on my openSUSE Linux with Gnome I have to be very careful how to specify the command. For example
`padsp adinrec test.wav`
will generate a lot of 
`Warning: adin_oss: no data fragment after 300 msec?`
messages and fragmented audio is recorded if the Gnome pulseaudio settings window is not open. Open this window, make no setting changes, and the problem goes away, recordings ok.

- attempting to use the "-input pulseaudio" option (legal according to help output) results in 
`STAT: ###### initialize input device
STAT: AD-in thread created
......................................Assertion 'pa_atomic_load(&(s)->_ref) >= 1' failed at pulse/stream.c:335, function pa_stream_get_state(). Aborting.`

- the tailmargin option value is a bit off. For example 
`-tailmargin 8000` results in silence after the audio of about 1000 ms.

Working around these issues means that adinrec is a good and valuable tool.

**Comment by nitslp-ri** [comment]
Hi, I want to clarify whether it is a problem of padsp/PulseAudio, or adinrec.  Does the first problem occurs in other tools that uses OSS API? and does the second problem occurs in other PulseAudio native audio tools in your environment?

For third problem, could you report in detail to reproduce it?

**Comment by colbec** [comment]
@nitslp-ri Other tools that use sound in my computer would be VLC, sox, Festival, Flite, Audacity plus alsa tools such as arecord and aplay for example. All of these seem to work on the device designated by PA. On my system PA runs all the time, controlling all audio.
1. One basic CLI command set that I use often for testing the audio system is 
`arecord -f DAT | aplay`
which just echoes back anything enunciated at the mike. The process uses the right device set without "no data fragment" messages whether the Gnome sound window is open or not. I don't know if this qualifies as a test for the first issue?
2. use/not of pulseaudio, here are some tests:
colin@linux-tqr4:~> adinrec file.wav
Warning: overwriting file "file.wav"
STAT: ###### initialize input device
Stat: adin_oss: device name = /dev/dsp (application default)
Error: adin_oss: failed to open /dev/dsp
Error in opening adin device
<<< please speak >>>^C[Interrupt]
0 samples (0 bytes, 0.00 sec.) recorded

colin@linux-tqr4:~> adinrec -input pulseaudio file.wav
Warning: overwriting file "file.wav"
STAT: ###### initialize input device
STAT: AD-in thread created
..........Error: adin_pulseaudio: pa_simple_read() failed: Bad state
Error: adin thread exit with error

12480 samples (24960 bytes, 0.78 sec.) recorded

colin@linux-tqr4:~> padsp adinrec file.wav
Warning: overwriting file "file.wav"
STAT: ###### initialize input device
Stat: adin_oss: device name = /dev/dsp (application default)
Stat: adin_oss: sampling rate = 16000Hz
Stat: adin_oss: going to set latency to 50 msec
Stat: adin_oss: audio I/O Latency = 32 msec (fragment size = 512 samples)
STAT: AD-in thread created
............        (here the process ended while I was still inputting audio)
13827 samples (27654 bytes, 0.86 sec.) recorded

colin@linux-tqr4:~> padsp adinrec -input pulseaudio file.wav
Warning: overwriting file "file.wav"
STAT: ###### initialize input device
STAT: AD-in thread created
..........Assertion 'pa_atomic_load(&(s)->_ref) >= 1' failed at pulse/stream.c:335, function pa_stream_get_state(). Aborting.
Aborted
3. Assume that we want to record a file until adinrec perceives 1 sec of silence. a priori without prejudice we choose the command 
`padsp adinrec -tailmargin 1000 file.wav`
adinrec starts recording as soon as it hears voice, good, but as I am speaking it suddenly shuts down after about 1-2 secs of recording as I am speaking. With
`padsp adinrec -tailmargin 8000 file.wav` 
the recording does not shut down suddenly, cuts out after speaking finished, but has silence at end of 2 to 4 seconds; the end silence seems quite variable. I guess this means that I need to play with the lv and zc options, but even so, at the default level the end silence should be at least 8 seconds?

**Comment by nitslp-ri** [comment]
@colbec Thanks for the report.  I'm using Ubuntu 14.04.

`adinrec -input pulseaudio file.wav` worked fine on my Ubuntu. From the error message it seems that the error comes from the internal part of PulseAudio.  I don't know why the behavior differs among distributions...

`-input alsa` also works for me.  Could you try using the alsa interface (without padsp)?

For `-tailmargin` option, did you adjust the trigger level threshold by `-lv`?  Its default value of 2000 is rather high, and not-so-loud speech will be mis-detected as silence.
Setting lower value (ex. `-lv 1000`) may ease the problem.

**Comment by colbec** [comment]
@nitslp-ri For tailmargin, I have now tried the -lv option and it helps overall to define where to start and stop recording. A value of 250 seems to be ok here. But it does not have much effect on the tailmargin issue. Tailmargin is quite important for situations where you are in the middle of a prompt and there is a slight hesitation. You don't want the system to think that the prompt ends at that point, and the default of 400 is really only suitable for very continuous input with no hesitations. Right now everything is cool, I just experiment and find a value, whatever it may be, which gives me on average one second of permissible hesitation.

**Comment by colbec** [comment]
@nitslp-ri After persistent problems with pulseaudio randomly throwing errors (as above) during otherwise good recordings with adinrec I have gone back to sox with silence option. I'm pretty sure as you say that the issues are in PA and not adinrec. Maybe in an upcoming new version all will be resolved again.

> Next I'll try reproducing -tailmargin 8000 error, within a few days.

Please don't put a priority on this, it may be my misunderstanding of what the parameter is intended to do. In `sox` it seems that even if you ask for a terminating x seconds of silence, it will only be used to determine end of recording; the result audio is trimmed both ends anyway.

**Comment by nitslp-ri** [comment]
@colbec OK, It is good that things are clarified. Thanks for the report!  If any progress, please re-open this issue.
