### ISSUE TITLE
Missing flags for nextword and mkbingram

### ISSUE THREAD

**Issue by palles77** [julius-speech/julius#12]
Hi

I am compiling Julius under Cygwin. I noticed that 2 flags were missing from mkbingram/Makefile.in and gramtools/nextword/Makefile.in which prevented proper compilation
The first one was missing a library '-libiconv'
The second one was missing a library '-lncurses'
Could you please add these to repository?

Thx
Leslaw

**Comment by nitslp-ri** [comment]
Hi,

Thanks for the report.  I've checked around the configuration script and fixed several bugs.

The fixed codes are at a new branch "fixconfigure".  Could you try it?

https://github.com/julius-speech/julius/tree/fixconfigure

If it's OK, I'll merge it into master (main source tree).

Thanks,

**Comment by palles77** [comment]
I can confirm it's working fine now with my Cygwin. Thank you for resolving that.
