### ISSUE TITLE
ERROR: m_jconf: failed to open jconf file: julius.jconf

### ISSUE THREAD

**Issue by yasuyasu-w** [julius-speech/julius#135]
### input
../julius/julius/julius -C mic.jconf -dnnconf dnn.jconf

### output
STAT: include config: julius.jconf
ERROR: m_jconf: failed to open jconf file: julius.jconf
Try `-help' for more information.

derectly is c/Users/MyUserName/ENVR-v5.4.Dnn.Bin

**Any suggestions?**

**Comment by INeddHelp** [comment]
how did you fix that i have the same error
