### ISSUE TITLE
Request for introductory information

### ISSUE THREAD

**Issue by forthrin** [julius-speech/julius#138]
Came across this as I've been interested in offline solutions for speech recognition. Some questions that immediately comes up when evaluating this type of software:

1. How far off from state of the art (ie. Siri) is it? Quite close, or years off and more an enthusiast/researcher level? If the latter, by which year do you estimate to catch up?

2. Does yielding optimal results require extensive technical insight to set up configuration files correctly, or do optimal results mostly come out of the box?

3. Does it handle background sound and music well, or is it mostly suited for isolated voice recordings?

4. Does it create a context from previous content in a file? Eg. if a guy says "Wisconsin" at 1:00, and (probably) again at 3:00, does the parser increase the probability that he did in fact say "Wisconsin"?

5. Does it consider word frequency, ie. assume that a speaker more likely said a commonly spoken word (in the world, not the file) rather than a very uncommon word that resembles the common word?

6. Does it consider syntax/grammar, or is it completely word-by-word? (Judging from quick tests I did, the latter is true).

7. The code base compiled quickly, and is presumably rather small. The learning binaries for English are 400 MB (zipped). Do you have a projection of how small necessary binaries can theoretically be made in the future? (For use in devices with minimal hardware/storage.) Alternatively, how many percent can binaries by shaved off by eliminating uncommon words in everyday speech?

8. Which are the top open source alternatives to offline speech recognition?

Thanks in advance for good answers, and if possible, add this information to your README to lower the introduction threshold for other interested parties.

**Comment by nitslp-ri** [comment]
1.  Siri and other engines are mainly cloud based, it can not be compared directly with Julius.  Recognition accuracy depends on models, not the engine itself.
2.  Optimal parameters are dependent on task models.  The default values are tuned for default model kit, so it shows optimal performance only for the default kit, but when you are applying Julius to other tasks, parameter fine-tune is required to get optimal result.
3.  Julius has a simple voice detection but NO noise suppression.  Currently it can not be used on background sound or music.
4. No, it perform recognition input by input without seeing context.
5. No speaker adaptation is included in Julius
6. Both grammar-based and N-gram-based recognition is supported.
7. Julius's memory footage for work area is less than 30 MBytes, most memories are occupied by language model and acoustic models.  There are many techniques to size down DNN-HMM, and it should be done outside Julius. 
8. I don't know the current status of open-source speech recognition toolkit.

**Comment by forthrin** [comment]
Thanks for your kind reply. At least for me, with no academic background in audio processing, would find it hard to configure and tweak this to give good results for a given speech recording. Hopefully, there will be other projects who abstract/adapt the technology to make it more accessible.
