### ISSUE TITLE
Reading memory past allocation calc_dnn.c#L831 dst = dnn->work[++n];

### ISSUE THREAD

**Issue by dlmiles** [julius-speech/julius#143]
https://github.com/julius-speech/julius/blob/ff5cd0f59d36c8ca722acf276083b8599737b4ff/libsent/src/phmm/calc_dnn.c#L831

valgrind reports this is reading memory 8 bytes past the end of the allocated memory.  I assume this is just before the for() loop exits due to "hidx >= dnn->hnum" become true at the start of the next iteration.

Consider just having "++n;" and moving all references to setting the variable "dst" to be the first statement inside the for() loop.

``for(hidx = 0; hidx < dnn->hnum; hidx++) {
  dst = dnn->work[n];
  /* SNIP statements not included in this example */
  n++;  /* or ++n; */
}``

Consider if "n" and "hidx" ever have a different value, maybe the compiler will optimize this out anyway and use a single counter variable?  Especially so if the above change is made. 

Unfortuantely is has OPENMP optimizations around it, and I have no idea how this change will affect this or if the reasons it is written as it is, is due to a performance improvement.

I assume the following locations are also affected:

https://github.com/julius-speech/julius/blob/ff5cd0f59d36c8ca722acf276083b8599737b4ff/libsent/src/phmm/calc_dnn.c#L847

**Comment by nitslp-ri** [comment]
You are right, the part apparently  has a redundancy.  I fixed them on d75aea0.  Thanks for your suggestion!
