### ISSUE TITLE
Help me find language models

### ISSUE THREAD

**Issue by Valery813** [julius-speech/julius#146]
Help me with links to models of different languages ​ ​ (Japanese, Slovenian, Thai). Where can I find documentation so I can make models for Julius myself?

**Comment by Estalhun** [comment]
http://www.voxforge.org/home/dev

**Comment by Valery813** [comment]
Thank you, follow the link small models of languages. I need bigger models.

**Comment by Valery813** [comment]
The Japanese language model, for example. But I only found it 20K words. Is there another one for more words?

**Comment by palles77** [comment]
I trained the language model for Polish and English on data scraped from the internet. However there are resources such as: https://aws.amazon.com/datasets/google-books-ngrams/, http://data.statmt.org/ngrams/deduped/. First of all you need corpus and than a ngram modelling library such as SRILM http://www.speech.sri.com/projects/srilm/manpages/ngram.1.html

**Comment by Valery813** [comment]
Thank you

**Comment by Valery813** [comment]
Thank you
