### ISSUE TITLE
Does julius wait to get all audio data before processing?

### ISSUE THREAD

**Issue by MayamaTakeshi** [julius-speech/julius#166]
I'm testing sending audio via adinnet and from my tests so far it seems julius waits for all the data to arrive before processing it.
I put 5 seconds of silence in the audio between phrases hoping julius would process each phrase as they arrive. But it seems first it gets all the audio then splits the phrases and process them.
Can someone confirm this?

**Comment by MayamaTakeshi** [comment]
Replying to myself, no, julius processes VAD and will handle a speech segment after silence is detected.
I was mislead in my tests because my implementation of my adinnet client app was flawed but partially worked.
See https://github.com/julius-speech/julius/issues/30#issuecomment-856461359)

**Comment by Estalhun** [comment]
You need to split the audio stream to segments shorter than 20 sec, or Julius will cut it at 20 sec. 
It is very serious problem when Julius slit a word apart becuse WER will be very high.
So, you have to detect non speech data (breath, silence) to split the stream to segments.
You can use the Julius GMM detector to classify the audio frame as speech or non-speech.
