### ISSUE TITLE
julius-simple doesn't recognize -help flag

### ISSUE THREAD

**Issue by nurupo** [julius-speech/julius#19]
I have grabbed the precompiled Linux binaries for Julius ([julius-4.3.1-linuxbin.tar.gz](http://osdn.jp/projects/julius/downloads/60273/julius-4.3.1-linuxbin.tar.gz/)), built and tried to run `julius-simple` to see Julius at work, but I wasn't able to do anything with it. It does react to `-setting`, but `-help` doesn't seem to work. My system is Debian Jessie x86-64.

```
$ ./julius-simple 
Julius rev.4.3.1 - based on 
JuliusLib rev.4.3.1 (fast)  built for x86_64-unknown-linux-gnu

Copyright (c) 1991-2013 Kawahara Lab., Kyoto University
Copyright (c) 1997-2000 Information-technology Promotion Agency, Japan
Copyright (c) 2000-2005 Shikano Lab., Nara Institute of Science and Technology
Copyright (c) 2005-2013 Julius project team, Nagoya Institute of Technology

Try '-setting' for built-in engine configuration.
Try '-help' for run time options.
```

```
$ ./julius-simple -help
ERROR: m_options: wrong argument: "-help"
Try `-help' for more information.
```

```
$ ./julius-simple --help
ERROR: m_options: wrong argument: "--help"
Try `-help' for more information.
```

```
$ ./julius-simple help
ERROR: m_options: wrong argument: "help"
Try `-help' for more information.
```

```
$ ./julius-simple -setting
JuliusLib rev.4.3.1 (fast)

Engine specification:
 -  Base setup   : fast
 -  Supported LM : DFA, N-gram, Word
 -  Extension    :
 -  Compiled by  : gcc -O6 -fomit-frame-pointer

Library configuration: version 4.3.1
 - Audio input
    primary A/D-in driver   : alsa (Advanced Linux Sound Architecture)
    available drivers       : alsa oss
    wavefile formats        : RAW and WAV only
    max. length of an input : 320000 samples, 150 words
 - Language Model
    class N-gram support    : yes
    MBR weight support      : yes
    word id unit            : short (2 bytes)
 - Acoustic Model
    multi-path treatment    : autodetect
 - External library
    file decompression by   : zlib library
 - Process hangling
    fork on adinnet input   : no

Try `-help' for more information.
```

**Comment by colbec** [comment]
I could be wrong, but don't think that `julius-simple` is intended to be anything more than an example of how to use the backend library of Julius, which makes a lot of assumptions about how it will be called. Some input args are handled correctly by julius simple, others are missing. I think it is up to the programmer to add, and delete, what is necessary to get it responding according to their priorities.

**Comment by nurupo** [comment]
Well, judging from the code, I would expect `julius-sample` to do more than just handling `-setting` flag and exiting, otherwise why is there all this code? If it's intended to be an example of how to use Julius library and the only working part of ithe example is the `-setting` handling, it's quite a poor example, wouldn't you agree?

**Comment by nitslp-ri** [comment]
It is a bug that `julius-simple` contains messages about `-help`.  `julius-simple` does not have option `-help`.  I'll remove it
