### ISSUE TITLE
m_jconf error in the linux terminal

### ISSUE THREAD

**Issue by INeddHelp** [julius-speech/julius#191]
STAT: include config: julius.jconf
ERROR: m_jconf: failed to open jconf file: julius.jconf
Try `-help' for more information.

how can i fix this error

**Comment by arcmirror** [comment]
I just ran into the same problem today and spent several hours trying to figure it out, not sure if this is the correct solution but it seemed to fix the m_jcomf error.

First of all, make sure you have all the files extracted from the zipped ENVR-v5.4.DNN.Bin.zip from the [sourceforge](https://sourceforge.net/projects/juliusmodels/files/). I noticed that I was missing the last couple of files from the zip, something just extracted weird. This included the julius.config file.

The second thing I did was put the Julius folder inside the ENVR-v5.4.Dnn.Bin folder. This allows the computer to grab both the ./julius/julius/julius and the julius.jconf files, if you run the  `% ../julius/julius/julius -C julius.jconf -dnnconf dnn.jconf ` command from the ENVR-v5.4.Dnn.Bin. directory (the same location you are in a the end of step 2)
