### ISSUE TITLE
How to get recognition results back to adintool/adinnet

### ISSUE THREAD

**Issue by Picolabo** [julius-speech/julius#2]
This is a question about how to get the recognition result back when we use adintool ( –out adinnet) to send a file to Julius (-input adinnet)

If I send a .wav file to Julius with adintool:

echo "file.wav" | adintool -in file -out adinnet -server localhost

(Julius started on localhost with -input adinnet)

Then I can see the recognition results on Julius' standard output, but I don't get any result on the client side (adintool).

How can I get the recognition results back to the client/adintool?

Thanks.

**Comment by nitslp-ri** [comment]
Recognition result can be sent in a different port. Run julius with "-module", and then connect to the network port to get the result.  See the sample client "jclient-perl" and "jcontrol" in the archive for details.

You can use both "-input adinnet" and "-module" in Julius, in such case Julius will receive audio stream from adintool and send recognition result to module client.  If you want to do the client side in one application, you should connect to the both port and listen to the module port while sending audio.

Thanks,

**Comment by Picolabo** [comment]
Thanks, now I understand that the stream has to be sent to the adinnet port and the result is received on the module port, but there is only one module port, so can I use Julius as a speech recognition server?

I mean, if at the same time:
- with process 1 I send voice stream 1 on adinnet port with client socket 1,
- with process 2 I send voice stream 2 on adinnet port with client socket 2,
then will I get 2 results on the module port?

And is there a way to tell that the result 1 comes from process 1 and the result 2 comes from the process 2?

Thanks.

**Comment by Picolabo** [comment]
Thanks, now I understand that the stream has to be sent to the adinnet port and the result is received on the module port, but there is only one module port, so can I use Julius as a speech recognition server?

I mean, if at the same time:
- with process 1 I send voice stream 1 on adinnet port with adintool,
- with process 2 I send voice stream 2 on adinnet port with adintool,

then I will get 2 results on the module port, right?

So is there a way to tell that the result 1 comes from process 1 and the result 2 comes from the process 2?

Thanks.

**Comment by Picolabo** [comment]
Thanks for your answer. What I would like to do is run only one instance of Julius behind a web server (so that the language model be loaded only once), so does Julius support sending several audio streams at the same time (with adintool for example)?
If it is the case then how can I pair the results on the module port with the corresponding audio streams (because there is no ID of some sort in the result, right?) 
Thanks.

**Comment by nitslp-ri** [comment]
I'm sorry that Julius can receive only one audio stream.  To handle multiple input/output pairs as a speech recognition server, it is better to use single socket for both sending audio and receiving result.  That can be accomplished by modifying Julius:
- Do not use module mode, use just "-input adinnet". Module mode makes Julius block until some client connect comes.
- Fork when accepting adinnet connection.
- Send the recognition result from stdout to the connected adinnet port.

Thanks,

**Comment by nitslp-ri** [comment]
Close this issue.  Please re-open for more question about this topic.
