### ISSUE TITLE
ERROR: m_chkparam:

### ISSUE THREAD

**Issue by CaredduMattia** [julius-speech/julius#27]
I've installed julius 4.3 from source file.
When i try to run : 
`julius -C julius.jconf -input mic`
I get : 

> STAT: include config: julius.jconf

And then nothing happen. Now if i check julius.log file i get : 

```
ERROR: m_chkparam: cannot access sample.dict
ERROR: m_chkparam: cannot access sample.dfa
ERROR: m_chkparam: cannot access hmm15/hmmdefs
ERROR: m_chkparam: cannot access tiedlist
ERROR: m_chkparam: could not pass parameter check
```

What could cause that problem?
Thanks.

**Comment by colbec** [comment]
If Julius cannot see the files it may mean they are not in your path. Check that before you start Julius you dive down to the path where the files live. So "cd" your way down there, then "ls sample.dict" to see that sample.dict actually lives there, then start Julius. If that does not work, post back.

**Comment by CaredduMattia** [comment]
Yes, the files doesn't exist. Where I can find that file? I solved for sample.dict sample.dfa and hmmdefs that i find online. But the others? Thanks.

**Comment by colbec** [comment]
The dict, dfa hmmdefs and tiedlist are files that make up your audio/language model. You would normally get these files as a result of following a training procedure as outlined in http://voxforge.org/home/dev "Acoustic Model Creation Tutorials" (for example). Or perhaps you have found a model that provides the files without requiring training. Either way, develop or download, the package would provide these files. Place them in a known location, navigate to them and launch Julius. Until they are in place Julius cannot load the model.
