### ISSUE TITLE
No easy way to check whether JuliusLib is installed

### ISSUE THREAD

**Issue by GeorgesStavracas** [julius-speech/julius#33]
JuliusLib, the static library distributed by Julius, doesn't provide pkg-config files so that build projects can transparently check whether the target system has Julius installed or not.

**Comment by GeorgesStavracas** [comment]
The Pull Request above adapts JuliusLib to generate a distro-agnostic, versioned .pc file, since Julius has major version bumps. Please, let me know if there's anything else I can do here :)

**Comment by nitslp-ri** [comment]
Thanks! I've incorporated it into 4.4.

**Comment by nitslp-ri** [comment]
The cflags and libs for libsent changes at compilation time, so the .pc file should contain flags determined at configuration process by libsent/configure.  I guess libsent should also have .pc file like libjulius, and determine dependency from libjulius to libsent.

**Comment by GeorgesStavracas** [comment]
Thanks for the comments. I was avoiding adding another .pc file, because I mistakenly thought it'd be an overkill. I'm actually happy to learn you want a .pc file for libsent as well, because that's the correct way to solve this problem.

Just updated the Pull Request with your comments.

**Comment by nitslp-ri** [comment]
Merged.  Thanks for your contribution!
