### ISSUE TITLE
Julius 4.4 compilation error on Cyginw

### ISSUE THREAD

**Issue by palles77** [julius-speech/julius#36]
Julius 4.4 cannot be compiled on Cygwin. I had to modify calc_dnn.c in lines:
14: #undef AVX
381:     float x = 0.0f;

to get it compiling on Cygwin with the following config:
bash configure --enable-sp-segment --enable-words-int --with-mictype=portaudio

**Comment by nitslp-ri** [comment]
Could you try giving "-mavx" option to gcc?

`bash CFLAGS='-mavx -O3' configure ...`

**Comment by nitslp-ri** [comment]
The code has been fixed.  Could you try the newest version on master branch?

**Comment by nitslp-ri** [comment]
More info about installation: 

Recently I added "INSTALL.txt" on the top directory, which describes the compilation and installation procedures on most OS, including required packages to build Julius.  If you have any trouble to compile please refer to the document.
