### ISSUE TITLE
Build breakage on AVX2

### ISSUE THREAD

**Issue by GeorgesStavracas** [julius-speech/julius#37]
The latest libsent from the `master` branch is broken because it uses AVX2 target without actually adding that target.

**Comment by nitslp-ri** [comment]
On my system (Ubuntu 14.04.4 LTS / gcc-4.8.4), the first test without "-mavx" actually produces error, and the second test with "-mavx" succeeds.  "-mavx" is not an option all the compiler should accept (although guess most of them will accept), so I want to try first to refine the first test to fail when the compiler does not support AVX instruction.  Changing the line  
` ],[__m256 v;],`
in configure.in to other test code like this
`],[__m256 v = _mm256_setzero_ps()],`
Does this works for you?

**Comment by nitslp-ri** [comment]
I tested on my cygwin and reproduced the error.  Checking with `_mm256_setzero_ps` worked for me, so updated the libsent/configure script.

Thanks for your report, this issue will be closed.

**Comment by GeorgesStavracas** [comment]
Ah, much better. The new test condition works for me, running on Arch Linux and using GCC.

Thanks for the quick fix!
