### ISSUE TITLE
Duplicate line in startup report output 

### ISSUE THREAD

**Issue by colbec** [julius-speech/julius#43]
Just a tiny thing, but in the startup report there is a duplicate line relating to "long-term DC removal". I think the line involved is in https://github.com/julius-speech/julius/blob/master/libjulius/src/m_info.c where there is a test for a flag; the test can produce DC removal off, then after the test there is a second printing of DC removal off. I think one of the lines is superfluous.

I tried to submit this as a pull request, but on completion of the process that would authorize me to make a pull request from my own fork of Julius I was informed that "Sorry, something went wrong." So I am able to edit my own fork, but not able to make the comparison between my fork and the Julius master to initiate a PR. Sorry, I tried.

**Comment by GeorgesStavracas** [comment]
Where is the flag test?

**Comment by GeorgesStavracas** [comment]
Oops, just found it

**Comment by colbec** [comment]
@GeorgesStavracas Thanks for that, exactly what I was thinking.

I just revisited my fork of Julius and found that I was now able to compare a revised branch in my fork with the Julius master, so perhaps next time I can send in a PR.

**Comment by nitslp-ri** [comment]
Thanks @colbec and @GeorgesStavracas !  I merged the fix into master.
