### ISSUE TITLE
I found a bug.

### ISSUE THREAD

**Issue by CazYokoyama** [julius-speech/julius#5]
Here is commit message.
By unknown reason, the file with .grammer as its extention is
    "can't open".
    [caz@ventus tophat]$ mkdfa.pl kaden
    cannot open "kaden.grammar" at mkdfa.pl line 69.

diff --git a/gramtools/mkdfa/mkdfa.pl.in b/gramtools/mkdfa/mkdfa.pl.in
index 495c329..ea347d6 100755
--- a/gramtools/mkdfa/mkdfa.pl.in
+++ b/gramtools/mkdfa/mkdfa.pl.in
@@ -56,7 +56,7 @@ foreach $arg (@ARGV) {
 if ($gramprefix eq "") {
     usage();
 }
-$gramfile = "$ARGV[$#ARGV].grammar";
+$gramfile = "$ARGV[$#ARGV].grm";
 $vocafile = "$ARGV[$#ARGV].voca";
 $dfafile  = "$ARGV[$#ARGV].dfa";
 $dictfile = "$ARGV[$#ARGV].dict";

How can I submit this kind of bug and improvement?
-caz, caz at caztech dot com
P.S. I am integrating julius into glide computer called Tophat which is used by glider pilot.

**Comment by nitslp-ri** [comment]
Hi, thanks for using Julius.

Could you tell us your environment (OS, file system, hardware etc)?
I guess It is not a bug of Julius, may be a limitation of your environment.  Your system may not allow extension longer than 3 letters, I want to confirm that.

Thanks,

**Comment by CazYokoyama** [comment]
I'm using fedora18 so that there is no limit on the number of extensions.
I'll let you know more detail tomorrow.

**Comment by colbec** [comment]
@CazYokoyama please check the extension of your .grammar file - in your OP the extension is .grammer and not .grammar - so when mkdfa.pl uses the stem it will not find a .grammar since only .grammer exists. Possible?

**Comment by CazYokoyama** [comment]
Colin,
You are correct. Simple mistake. Thx.
-caz


On Mon, Dec 7, 2015 at 10:03 AM, Colin Beckingham <notifications@github.com>
wrote:

> @CazYokoyama <https://github.com/CazYokoyama> please check the extension
> of your .grammar file - in your OP the extension is .grammer and not
> .grammar - so when mkdfa.pl uses the stem it will not find a .grammar
> since only .grammer exists. Possible?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julius-speech/julius/issues/5#issuecomment-162609612>.
>



-- 
-caz, caz@caztech.com, 503-804-1028(m)

**Comment by nitslp-ri** [comment]
@colbec @CazYokoyama  Thanks!
