### ISSUE TITLE
How does the -inactive option work?

### ISSUE THREAD

**Issue by colbec** [julius-speech/julius#54]
If I try to run Julius (JuliusLib rev.4.4.2 (fast)) with the -inactive option such as 
`julius -inactive -C some.jconf` then the result is an infinite loop of 
```

WARNING: pause requested but no pause function specified
WARNING: engine will resume now immediately
```

**Comment by nitslp-ri** [comment]
`-inactive` lets Julius start with paused status and blocks until resume command comes.  It works only when adequate pause/resume function is specified, i.e., module mode.
