### ISSUE TITLE
Convert the library to NDK build for Android use

### ISSUE THREAD

**Issue by saran2somu** [julius-speech/julius#56]
Hi, 
   Anyone is integrate the  "julius" library for android , please list the step how to integrate or How to build the ndk library.

**Comment by nitslp-ri** [comment]
There is no native support for Android jni, but there is a Julius-based library "Library_Julius" in MMDAgent, and it can be built for Android ndk.  The source code of MMDAgent, especially the file "Library_Julius/Android.mk" may help you.

https://mmdagent.jp/
