### ISSUE TITLE
-lasound missing when doing make all

### ISSUE THREAD

**Issue by JL85** [julius-speech/julius#60]
```
make[1]: Entering directory '/home/john/.local/share/Trash/files/julius-4.4.3.1/julius'
gcc -m32 -I. -I../libjulius/include -I../libsent/include  `../libsent/libsent-config --cflags` `../libjulius/libjulius-config --cflags` -o julius main.o recogloop.o module.o output_module.o output_stdout.o output_file.o record.o charconv.o charconv_iconv.o -L../libjulius `../libjulius/libjulius-config --libs` -L../libsent `../libsent/libsent-config --libs`  
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
Makefile:58: recipe for target 'julius' failed
make[1]: *** [julius] Error 1
```
I am using Ubuntu Xenail 64 bit and  i am stuck at missing lasound..

i have gone thrue all thies steps and there all fixed:

- .Bash_profile does not exist (VoxForge for Julius STT)
- Finding .bash_profile and adding path's
- yum install alsa-lib-devel.i686 (yum and alsa-lib-devel.i686 does not exist as package)
- installation or configuration problem: C compiler cannot create executables.
- Jcode.pm missing

**OBS: I am doing a installing problem thread too so if you want i can message you the rest upcoming problems**

**Comment by colbec** [comment]
Looks like your alsa libraries are either not installed or not available.
Go back to your ./configure step and examine the output for entries related to alsa and see if it gives you clues.
See if yum allows you to search the appropriate repositories for the right name for the alsa development package and try again.
