### ISSUE TITLE
Silent failures in ./configure

### ISSUE THREAD

**Issue by DavidGriffith** [julius-speech/julius#64]
The chained autoconf seems to be causing failures that aren't reported at the end of ./configure's execution.  Two that I've noticed so far are these:

(for gramtools)
```
checking for Jcode module in perl... Can't locate Jcode.pm in @INC (you may need to install the Jcode module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base).
BEGIN failed--compilation aborted.
configure: WARNING: no Jcode module in perl, gram2sapixml.pl may not work
```

Then these things in lots of places:
```
checking for dlopen... ./configure: line 1600: ac_fn_c_try_link: command not found no
checking for gethostbyname... ./configure: line 1751: ac_fn_c_try_link: command not found no
```

The Perl complaint can be fixed by installing `libjcode-pm-perl`, but the instructions don't mention that.  I'm not sure how the second set of complaints can hurt anything since I know that those functions are indeed present and usable.

Then I come to `mkfa`.  For some reason, `make` is never run in `julius/gramtools/mkdfa/mkfa-1.44-flex`.  This causes `make install` in `julius/` to fail.

I'm running Debian 9 (Stretch) and I tried the master branch and the v4.4.2.1 tag.

**Comment by nitslp-ri** [comment]
Fixed in recent commit, thanks!
