### ISSUE TITLE
[Announce] new branch adintool-gui

### ISSUE THREAD

**Issue by nitslp-ri** [julius-speech/julius#7]
Hi, just announcing an experimental feature.

A new branch "adintool_gui" has been created which includes an experimental GUI version of adintool.
You can see how audio is captured and voice is detected on live screen.  You can also adjust the trigger level threshold manually using keyboard, and tell server to force audio segmentation, on the fly.

![screenshot_adintool_gui](https://cloud.githubusercontent.com/assets/12009526/11736391/118aa486-a011-11e5-9cc1-23e38f9871a2.png)

You can try another very experimental feature, *automatic* trigger level adjuster.  To test it, define AUTO_ADJUST_THRESHOLD in adintool.h.  The algorithm is based on simple amplitude mean/variance.  It is just a tiny hack and not stable, so do not use this on a critical system.

Checkout the "adintool-gui" branch, configure & make, then execute adintool/adintool.  You need SDL2 library to compile.  See "adintool/GUI_SDL2.txt" for details.  I've tested it on Windows and Linux.

**Comment by colbec** [comment]
@nitslp-ri When configuring on openSUSE with sdl2 libraries installed, configure process produces error on:
...
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
Makefile:38: recipe for target 'adintool' failed
make[1]: *** [adintool] Error 1
...

Yast shows that asound libraries are installed as "libasound2", from the file listing I have 
/usr/lib64/libasound.so.2
/usr/lib64/libasound.so.2.0.0

32 bit versions are also installed.

The configure process continues and appears to complete correctly, even though the error perhaps should have stopped the configure.

**Comment by colbec** [comment]
@nitslp-ri Oops my fault, the alsa libraries have devels in alsa-devel on opensuse, all ok for configure now.

**Comment by colbec** [comment]
I spoke too soon, configure still fails on 
...
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lts
collect2: error: ld returned 1 exit status
...
From my reading -lts could be a number of things including freetype, however installing that package heads into a large number of package installations on my system so I am hesitant. What does ts refer to in this case please?

**Comment by nitslp-ri** [comment]
The linker option "-lts" is not in the Makefile.in of adintool, so maybe it's required by SDL2.  Could you check the output of "sdl2-config --static-libs"?  Adintool simply passes the output of this command to linker.

Did you installed all the packages required for libsdl2? On Ubuntu you can install them by
```
% sudo apt-get install libsdl2-dev
```

Or changing the "sdl2-config --static-libs" in Makefile to "sdl2-config --libs" works?

**Comment by colbec** [comment]
I am using openSUSE:

> sdl2-config --static-libs
-L/usr/lib64 -lSDL2 -lpthread -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lts -lpthread -lrt

> sdl2-config --libs
-L/usr/lib64 -lSDL2 -lpthread

with this change, configure runs without referring to -lts.
Did make clean && make
But I'm still not seeing anything referring to a gui. 
my command is "padsp adintool -in mic -out stdout
where stdout is the only option that works for me so far
"padsp adintool -in mic -out "test.wav" fails with error on -out options

**Comment by nitslp-ri** [comment]
Could you try
```
padsp adintool -in mic -out file -filename test
```
(will record triggered samples to test0000.wav, test0001.wav,...), or
```
padsp adintool -in mic -out none
```
(will capture audio but output nothing)

**Comment by colbec** [comment]
Command
`padsp adintool -nostrip -in mic -out file -filename test`
is good, providing text only output and storing to file. No sign of GUI type output.

Command `padsp adintool` gives help output
Command `padsp adintool -in mic -out none` gives 
> padsp adintool -nostrip -in mic -out none
Error: no such output device: none
ERROR: useropt_exec: "-out" function returns FALSE
ERROR: m_options: error in processing "-out"
Error reading arguments

**Comment by nitslp-ri** [comment]
> padsp adintool -nostrip -in mic -out none
> Error: no such output device: none
> ERROR: useropt_exec: "-out" function returns FALSE
> ERROR: m_options: error in processing "-out"
> Error reading arguments

 I reproduced the same situation on master branch, it is a behavior of non-GUI version.  Could you make sure you are buildiong on `adintool_gui` branch?
```
cd $(repository_top)
make distclean
git checkout adintool_gui
./configure
make
```

**Comment by colbec** [comment]
@nitslp-ri Originally I switched to the `aintool_gui` branch on the github website and downloaded the zip package and ran from there in a separate directory. However, I followed your instruction above, did a distclean in the main git branch and switched to the required gui branch, and recompiled. I get the same behaviour as in my previous post. I'm not sure what I could be doing incorrectly. Is there a unique line or feature of the source or the configure output or the --version option that I can quickly check that would indicate that I am using the right build?

**Comment by nitslp-ri** [comment]
@colbec Is there definition of `USE_SDL` in Makefile? This definition switches GUI and CUI version.
```
SDL_CFLAGS=`sdl2-config --cflags` -DUSE_SDL
```

**Comment by colbec** [comment]
OK got it working. A number of issues 
1. each time I run configure from the main julius directory the Makefile in adintool is overwritten with the problem we found with `sdl2-config --static-libs` above, so on openSUSE build will fail
2. running make from the main directory causes the build in adintool to fail, but the compile/make just keeps going so user thinks all must be ok when the process ends without error
3. running make install does not overwrite the main system adintool executable because no executable is created locally if it fails, so calling the main adintool just behaves like the old adintool because that is what it is, the old version survives
4. so it is important to build adintool locally in that directory, see that the executable is created, and then call it as `padsp ./adintool -in mic -out none` note the ./ before adintool to point at the right version.

**Comment by nitslp-ri** [comment]
@colbec Good, and thanks for comments.  Now I have fixed top Makefile to stop building immediately at error in sub directories.  Now one can easily find that some error in one of the sub directories.

**Comment by nitslp-ri** [comment]
Merged to master, now build both `adintool` and `adintool-gui` when SDL2 library is installed in your environment.  See "adintool/README-GUI.txt" for details.
