### ISSUE TITLE
Potential data race in processPacket in zmean_reset and sub_zmean

### ISSUE THREAD

**Issue by ITWOI** [julius-speech/julius#79]
Hi all,

Our bug scanner has reported a data race issue from [zmean.c#L54](https://github.com/julius-speech/julius/blob/master/libsent/src/adin/zmean.c#L54) to [zmean.c#L85](https://github.com/julius-speech/julius/blob/master/libsent/src/adin/zmean.c#L85)

Followings are code snippets.

```c++
void
zmean_reset()
{
  zlen = 0;
  zmean = 0.0;
}
```

and

```c++
void
sub_zmean(SP16 *speech, int samplenum)
{
  ...
  if (zlen < ZMEANSAMPLES) {
    /* update zmean */
    sum = zmean * zlen;
    ...
    zmean = sum / (float)zlen;
  }
  for (i=0;i<samplenum;i++) {
    d = (float)speech[i] - zmean;
    ...
  }
}
```

` zmean` is a static variable and functions `zmean_reset` and `sub_zmean` could be executed parallelly. Therefore, when two threads reach the race point simultaneously, the result of operations with `zmean` in `sub_zmean` may be affected.

A possible call trace could be as follows:

`main_recognition_stream_loop` calls `j_open_stream` in a loop, which means the callee can be called more than once.

In `j_open_stream`, it calls `adin_thread_create`, which create a thread executing `adin_thread_input_main`. Then it calls `adin_cut` and in `adin_cut`, it calls `sub_zmean`.

At the second loop in `main_recognition_stream_loop`, it also calls `j_open_stream` and in `j_open_stream`, it calls `adin_begin`. Finally, it calls `zmean_reset`.

The type of race is also applicable to variable `zlen` in the same two functions `zmean_reset` and `sub_zmean`.

SourceBrella Inc.,
Yu

**Comment by nitslp-ri** [comment]
Thanks for the report.  The race may not occur actually since the device opened within j_open_stream() will be closed at the end of  j_recognize_stream().  Also the second open will occur only at file input and adin input, where threaded audio recording are disabled by default on those input devices.
